services:
  mongo:
    profiles: ["ci"]
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    # ports: ["27017:27017"]  # optional in CI; Compose DNS is enough
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

  # Production API (distroless runtime)
  api:
    profiles: ["prod"]
    build:
      context: ./api
      dockerfile: Dockerfile
      target: prod
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_TOKEN_TTL=${ACCESS_TOKEN_TTL:-20s}
    # Keep API internal; Nginx proxies /api to this service
    # ports: ["5000:5000"]

  # Production client (Nginx)
  client:
    profiles: ["prod"]
    build:
      context: ./client
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - api
    ports:
      - "8080:80"

  # Development API (hot reload)
  api-dev:
    profiles: ["dev"]
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ACCESS_TOKEN_TTL=${ACCESS_TOKEN_TTL:-20s}
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"

  # Development client (Vite)
    # Development client (Vite)
  client-dev:
    profiles: ["dev"]
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"